function purity= Purity(cluster,realclass)
n=length(intersect(cluster.group1(:,1),realclass.Clu.clu1(:,1)))+...
  length(intersect(cluster.group2(:,1),realclass.Clu.clu2(:,1)))+...
  length(intersect(cluster.group3(:,1),realclass.Clu.clu3(:,1)))+...
  length(intersect(cluster.group4(:,1),realclass.Clu.clu4(:,1)));
N=size(cluster.group1,1)+size(cluster.group2,1)+size(cluster.group3,1)+size(cluster.group4,1);
purity=n/N;
end